Repository LIKELION-Android-Bootcamp-4th/Cinemarket, pull requests merged in 2025-07, with the labels that each got.

#1 [MAIN-001] chore/setup-env
  analysis_options.yaml
  assets/fonts/Pretendard-Black.ttf
  assets/fonts/Pretendard-Bold.ttf
  assets/fonts/Pretendard-Light.ttf
  assets/fonts/Pretendard-Medium.ttf
  assets/fonts/Pretendard-Regular.ttf
  assets/fonts/Pretendard-SemiBold.ttf
  assets/fonts/Pretendard-Thin.ttf
  lib/core/router/router.dart
  lib/core/theme/app_colors.dart
  lib/core/theme/app_text_style.dart
  lib/features/cart/screen/cart_screen.dart
  lib/features/favorite/screen/favorite_screen.dart
  lib/features/home/screen/home_screen.dart
  lib/features/main/screen/main_screen.dart
  lib/features/movies/screen/movies_screen.dart
  lib/features/mypage/screen/mypage_screen.dart
  lib/features/products/screen/products_screen.dart
  lib/features/search/screen/search_screen.dart
  lib/main.dart
  lib/widgets/bottom_nav_bar.dart
  lib/widgets/common_app_bar.dart
  lib/widgets/main_app_bar.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, chore

#5 [f01/f02] 굿즈/영화 찜 목록 UI 구현
  lib/features/favorite/screen/favorite_screen.dart
  lib/features/favorite/widget/favorite_gridview.dart
  lib/features/favorite/widget/item_type.dart
  lib/widgets/goods_item.dart
  lib/widgets/movie_item.dart
Labels: ui

#8 feat : 공통 TabBar 위젯 생성
  lib/widgets/common_tab_view.dart
Labels: feature

#9 UI/view : 로딩, 새로고침 위젯
  lib/widgets/loading_view.dart
  lib/widgets/retry_view.dart
Labels: feature, ui

#13 Update pull_request_template.md
  .github/pull_request_template.md
Labels: chore

#10 [ui/g01] 전체 굿즈 목록 화면 UI 구현
  lib/core/router/router.dart
  lib/features/goods/screen/goods_screen.dart
  lib/features/main/screen/main_screen.dart
  lib/features/products/screen/products_screen.dart
  lib/widgets/bottom_nav_bar.dart
  lib/widgets/sort_dropdown.dart
  pubspec.lock
  pubspec.yaml
Labels: ui

#16 [ui/toast] 커스텀 토스트 위젯 생성
  lib/widgets/common_toast.dart
  pubspec.lock
  pubspec.yaml
Labels: ui

#19 [docs] pr template 내 스크린샷 관련 콜아웃 추가
  .github/pull_request_template.md
Labels: docs

#22 [UI/mv02] 영화 상세 화면 UI 구현
  lib/core/router/router.dart
  lib/features/home/screen/home_screen.dart
  lib/features/movies/screen/movie_detail_screen.dart
  lib/features/movies/widgets/cast_grid_view.dart
  lib/features/movies/widgets/cast_item.dart
  lib/features/movies/widgets/movie_detail_header.dart
  lib/features/movies/widgets/movie_info_row.dart
  lib/features/movies/widgets/synopsis_text.dart
Labels: ui

#25 [ui/R01] 리뷰 아이템 UI 구현
  lib/core/router/router.dart
  lib/features/login/screen/login_screen.dart
  lib/features/mypage/detail/component/edit_profile_component.dart
  lib/features/mypage/detail/component/fix_review_component.dart
  lib/features/mypage/detail/component/my_review_component.dart
  lib/features/mypage/detail/component/order_history_component.dart
  lib/features/mypage/detail/my_page_detail_screen.dart
  lib/features/mypage/screen/my_page_screen.dart
  lib/features/signup/screen/sign_up_screen.dart
  lib/widgets/review_item.dart
Labels: ui

#26 [Feature/MOVIE-001]
  lib/core/network/kobis_client.dart
  lib/core/network/tmdb_client.dart
  lib/features/home/model/box_office_movie.dart
  lib/features/home/model/tmdb_movie.dart
  lib/features/home/repository/home_repository.dart
  lib/features/home/screen/home_screen.dart
  lib/features/home/service/kobis_service.dart
  lib/features/home/service/tmdb_service.dart
  lib/features/home/viewModel/home_viewmodel.dart
  lib/features/home/widgets/best_goods_widget.dart
  lib/features/home/widgets/best_movie_widget.dart
  lib/features/home/widgets/box_office_ranking_widget.dart
  lib/features/home/widgets/recommended_goods_widget.dart
  lib/features/movies/screen/movie_detail_screen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, ui, refactor

#33 refactor: 리뷰 아이템 버튼 고정값 변경
  lib/widgets/review_item.dart
Labels: refactor

#36 [chore/add-gitignore] chore: ignore .env file in git & remove redundant
  .gitignore
Labels: chore

#34 [UI/or01-2] 장바구니 화면
  lib/core/router/router.dart
  lib/features/cart/screen/cart_screen.dart
  lib/features/cart/widgets/cart total_widgets.dart
  lib/features/cart/widgets/cart_bottom_bar_widgets.dart
  lib/features/cart/widgets/cart_control_bar_widgets.dart
  lib/features/cart/widgets/cart_empty_view_widgets.dart
  lib/features/cart/widgets/cart_item_tile.dart
  lib/features/cart/widgets/cart_item_widgets.dart
  lib/features/purchase/screen/purchase_screen.dart
  pubspec.lock
Labels: ui

#39 [feat/GOODS-002] 전체 굿즈 목록 조회 기능 구현
  lib/core/network/api_client.dart
  lib/core/router/router.dart
  lib/features/favorite/screen/favorite_screen.dart
  lib/features/goods/model/goods.dart
  lib/features/goods/model/goods_images.dart
  lib/features/goods/model/goods_response.dart
  lib/features/goods/model/pagination.dart
  lib/features/goods/model/review_stats.dart
  lib/features/goods/repository/goods_repository.dart
  lib/features/goods/screen/goods_all_screen.dart
  lib/features/goods/services/goods_service.dart
  lib/features/goods/viewmodel/goods_all_viewmodel.dart
  lib/features/movies/screen/movie_detail_screen.dart
  lib/features/movies/screen/movies_screen.dart
  lib/features/search/screen/search_screen.dart
  lib/main.dart
  lib/widgets/common_gridview.dart
Labels: feature

#42 [fix/GOODS-002] read -> watch로 변경
  lib/features/goods/screen/goods_all_screen.dart
Labels: fix

#40 [Feat/search 001] 검색 관련 기능
  lib/features/search/model/search_goods_model.dart
  lib/features/search/model/search_tmdb_model.dart
  lib/features/search/repository/search_repository.dart
  lib/features/search/screen/search_screen.dart
  lib/features/search/service/search_service.dart
  lib/features/search/viewmodel/search_view_model.dart
  lib/main.dart
Labels: feature

#44 [feat/GOODS-003] 굿즈 상세 조회 통신 구현
  lib/core/router/router.dart
  lib/features/goods/model/goods.dart
  lib/features/goods/model/goods_all_response.dart
  lib/features/goods/model/goods_detail_response.dart
  lib/features/goods/repository/goods_repository.dart
  lib/features/goods/screen/goods_detail_screen.dart
  lib/features/goods/services/goods_service.dart
  lib/features/goods/viewmodel/goods_all_viewmodel.dart
  lib/features/goods/viewmodel/goods_detail_viewmodel.dart
  lib/features/goods/widget/header_goods_detail.dart
  lib/features/goods/widget/tabs_detail.dart
  lib/main.dart
  lib/widgets/common_gridview.dart
Labels: feature

#45 [feat/MOVIE-004] 영화 상세 페이지 데이터 통신
  lib/features/movies/model/cast_member.dart
  lib/features/movies/model/tmdb_movie_detail.dart
  lib/features/movies/repository/movie_detail_repository.dart
  lib/features/movies/repository/movies_repository.dart
  lib/features/movies/screen/movie_detail_screen.dart
  lib/features/movies/screen/movies_screen.dart
  lib/features/movies/service/movies_service.dart
  lib/features/movies/viewmodel/movie_detail_viewmodel.dart
  lib/features/movies/viewmodel/movies_viewmodel.dart
  lib/features/movies/widgets/cast_grid_view.dart
  lib/features/movies/widgets/cast_item.dart
  lib/features/movies/widgets/movie_detail_header.dart
  lib/features/movies/widgets/movie_info_row.dart
  lib/main.dart
  lib/widgets/common_gridview.dart
Labels: feature

#46 [feat/GOODS-001] 베스트 굿즈 목록 서버 API 통신
  lib/core/model/list_response.dart
  lib/core/model/pagination.dart
  lib/core/model/success_response.dart
  lib/features/home/model/best_goods.dart
  lib/features/home/repository/best_goods_repository.dart
  lib/features/home/service/best_goods_service.dart
  lib/features/home/viewModel/best_goods_viewmodel.dart
  lib/features/home/widgets/best_goods_widget.dart
Labels: feature

#47 [feat/MOVIE-002] 베스트 영화 목록 TMDB 서버 통신
  lib/features/home/repository/best_movie_repository.dart
  lib/features/home/screen/home_screen.dart
  lib/features/home/service/tmdb_service.dart
  lib/features/home/viewmodel/best_movie_viewmodel.dart
  lib/features/home/viewmodel/home_viewmodel.dart
  lib/features/home/widgets/best_movie_widget.dart
  lib/features/home/widgets/box_office_ranking_widget.dart
  lib/main.dart
Labels: feature

#48 [feat/SIGNUP-001] 회원 정보 수정, 주소 검색 API 연동
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/core/router/router.dart
  lib/features/auth/repository/auth_repository.dart
  lib/features/auth/service/auth_service.dart
  lib/features/auth/viewmodel/my_page_viewmodel.dart
  lib/features/auth/viewmodel/sign_up_viewmodel.dart
  lib/features/goods/screen/goods_review_screen.dart
  lib/features/goods/widget/tabs_review.dart
  lib/features/mypage/detail/component/edit_profile_component.dart
  lib/features/mypage/detail/my_page_detail_screen.dart
  lib/features/mypage/detail/widget/edit_profile_widget.dart
  lib/features/mypage/detail/widget/fix_review_widget.dart
  lib/features/mypage/detail/widget/my_review_widget.dart
  lib/features/mypage/detail/widget/order_detail_widget.dart
  lib/features/mypage/detail/widget/order_history_widget.dart
  lib/features/signup/screen/sign_up_screen.dart
  pubspec.yaml
Labels: feature

#49 [feat/FAV-001] 찜 목록 조회 기능 구현
  lib/core/network/api_client.dart
  lib/core/theme/app_text_style.dart
  lib/features/favorite/model/favorite_item.dart
  lib/features/favorite/repository/favorite_repository.dart
  lib/features/favorite/screen/favorite_screen.dart
  lib/features/favorite/service/favorite_service.dart
  lib/features/favorite/viewmodel/favorite_viewmodel.dart
  lib/main.dart
  lib/widgets/common_gridview.dart
  lib/widgets/goods_item.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#52 [feat/GOODS-005] 영화 상세 페이지 상품 목록
  lib/features/goods/model/review_stats.dart
  lib/features/home/model/best_goods.dart
  lib/features/home/viewModel/best_goods_viewmodel.dart
  lib/features/home/widgets/build_best_goods_grid.dart
  lib/features/movies/repository/movie_detail_repository.dart
  lib/features/movies/screen/movie_detail_screen.dart
  lib/features/movies/service/movies_service.dart
  lib/features/movies/viewmodel/movie_detail_viewmodel.dart
  lib/features/movies/widgets/synopsis_text.dart
Labels: feature

#53 [feat/REVIEW-002,003] 나의 리뷰 목록 조회 통신 및 리뷰 삭제 기능 구현 완료
  lib/core/router/router.dart
  lib/features/goods/screen/goods_review_screen.dart
  lib/features/goods/widget/tabs_review.dart
  lib/features/mypage/detail/my_page_detail_screen.dart
  lib/features/mypage/detail/widget/fix_review_widget.dart
  lib/features/mypage/detail/widget/my_review_widget.dart
  lib/features/mypage/model/review.dart
  lib/features/mypage/model/review_image.dart
  lib/features/mypage/model/review_product.dart
  lib/features/mypage/repository/review_repository.dart
  lib/features/mypage/service/review_service.dart
  lib/features/mypage/viewmodel/review_viewmodel.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#54 [fix/SIGNUP-001] 회원가입 로직수정, 회원정보 누락코드 추가
  lib/features/auth/service/auth_service.dart
  lib/features/auth/viewmodel/sign_up_viewmodel.dart
  lib/features/mypage/detail/widget/edit_profile_widget.dart
  lib/features/signup/screen/sign_up_screen.dart
Labels: fix

#58 [fix/FAV-001] 비회원이 찜 추가 시 로그인 유도 화면으로 이동 기능 fix
  lib/features/favorite/service/favorite_service.dart
Labels: fix

#59 [feat/GOODS-006] 굿즈 상세 페이지 추천 굿즈 통신 및 출력
  lib/features/goods/model/goods.dart
  lib/features/goods/model/goods_images.dart
  lib/features/goods/repository/goods_recommended_repository.dart
  lib/features/goods/screen/goods_detail_screen.dart
  lib/features/goods/services/goods_recommended_service.dart
  lib/features/goods/viewmodel/goods_recommended_viewmodel.dart
  lib/features/goods/widget/common_tabs_content.dart
  lib/features/goods/widget/recommend_goods_widget.dart
  lib/features/home/widgets/build_best_goods_grid.dart
  pubspec.lock
Labels: feature

#61 [Feat/cart] 장바구니 조회 / 추가 / 삭제 & 주문생성 기능 구현
  lib/features/auth/viewmodel/my_page_viewmodel.dart
  lib/features/cart/model/cart_item_model.dart
  lib/features/cart/screen/cart_screen.dart
  lib/features/cart/service/cart_service.dart
  lib/features/cart/viewmodel/cart_viewmodel.dart
  lib/features/cart/widgets/cart_bottom_bar_widgets.dart
  lib/features/cart/widgets/cart_item_tile.dart
  lib/features/cart/widgets/cart_item_widgets.dart
  lib/features/purchase/info/shipping_info_form.dart
  lib/features/purchase/screen/purchase_screen.dart
  lib/features/purchase/widgets/delivery_info_cart.dart
  lib/main.dart
  pubspec.lock
Labels: feature

#63 [feat/REVIEW-004] 해당 굿즈에 대한 전체 리뷰 조회 기능 구현
  lib/core/router/router.dart
  lib/features/goods/model/goods_review.dart
  lib/features/goods/repository/goods_repository.dart
  lib/features/goods/screen/goods_detail_screen.dart
  lib/features/goods/screen/goods_review_screen.dart
  lib/features/goods/services/goods_service.dart
  lib/features/goods/viewmodel/goods_review_viewmodel.dart
  lib/features/goods/widget/tabs_review.dart
  lib/features/mypage/detail/widget/my_review_widget.dart
  lib/features/mypage/model/review.dart
  lib/main.dart
  lib/widgets/review_item.dart
Labels: feature

#60 [feat/ORDER-001 & DETAIL-001 & REVIEW-001] 주문 내역 통신 & 상세 주문 내역 통신 & 리뷰 작성 통신
  lib/core/router/router.dart
  lib/core/theme/app_text_style.dart
  lib/features/mypage/detail/my_page_detail_screen.dart
  lib/features/mypage/detail/widget/create_review_widget.dart
  lib/features/mypage/detail/widget/order_detail_widget.dart
  lib/features/mypage/detail/widget/order_history_widget.dart
  lib/features/mypage/model/order/order.dart
  lib/features/mypage/model/order/order_item.dart
  lib/features/mypage/model/order/order_item_product.dart
  lib/features/mypage/model/order/order_review.dart
  lib/features/mypage/model/order/shipping_Info.dart
  lib/features/mypage/model/order/status_history.dart
  lib/features/mypage/model/orderdetail/detail_shipping_info.dart
  lib/features/mypage/model/orderdetail/order_detail.dart
  lib/features/mypage/model/orderdetail/order_detail_item.dart
  lib/features/mypage/model/orderdetail/user_info.dart
  lib/features/mypage/model/review_request.dart
  lib/features/mypage/repository/order_detail_repository.dart
  lib/features/mypage/repository/order_repository.dart
  lib/features/mypage/repository/review_repository.dart
  lib/features/mypage/service/order_service.dart
  lib/features/mypage/service/review_service.dart
  lib/features/mypage/viewmodel/order_detail_viewmodel.dart
  lib/features/mypage/viewmodel/order_viewmodel.dart
  lib/features/mypage/viewmodel/review_viewmodel.dart
Labels: feature

#65 [refactor/MOVIE-001] 박스오피스 개봉일 날짜 색상 변경
  lib/features/home/widgets/box_office_ranking_widget.dart
Labels: ui, refactor

#66 [refactor/MOVIE-005] 박스오피스 데이터 클릭 시 영화 상세 페이지로 이동
  lib/features/home/widgets/box_office_ranking_widget.dart
Labels: refactor

#68 [Refactor/MAIN-002] 홈 화면 더보기 색상 변경 & 하단 추천 굿즈 위젯 삭제
  lib/features/home/screen/home_screen.dart
  lib/features/home/widgets/best_goods_widget.dart
  lib/features/home/widgets/best_movie_widget.dart
  lib/features/home/widgets/recommended_goods_widget.dart
Labels: ui, refactor

#69 [Refactor/MAIN-001] 바텀 네비게이션 데이터 로딩 문제 해결
  lib/features/goods/screen/goods_all_screen.dart
  lib/features/goods/viewmodel/goods_all_viewmodel.dart
  lib/features/home/screen/home_screen.dart
  lib/features/home/viewmodel/best_goods_viewmodel.dart
  lib/features/home/viewmodel/best_movie_viewmodel.dart
  lib/features/home/viewmodel/home_viewmodel.dart
  lib/features/home/widgets/best_goods_widget.dart
  lib/features/movies/screen/movies_screen.dart
  lib/features/movies/viewmodel/movies_viewmodel.dart
  lib/main.dart
  pubspec.lock
Labels: refactor, fix

#72 [fix/MAIN-001] 홈 화면 merge 후 수정
  lib/features/home/widgets/box_office_ranking_widget.dart
Labels: fix

#75 [Refactor/MOVIE-003] 영화 목록 관련 리팩토링
  assets/images/default_poster.png
  lib/features/home/model/tmdb_movie.dart
  lib/features/movies/repository/movies_repository.dart
  lib/features/movies/screen/movies_screen.dart
  lib/features/movies/service/movies_service.dart
  lib/features/movies/viewmodel/movies_viewmodel.dart
  lib/widgets/common_gridview.dart
  lib/widgets/movie_item.dart
  lib/widgets/sort_dropdown.dart
Labels: ui, refactor

#76 [Refactor/MOVIE-004]
  lib/features/home/widgets/build_best_goods_grid.dart
  lib/features/movies/model/tmdb_movie_detail.dart
  lib/features/movies/repository/movie_detail_repository.dart
  lib/features/movies/screen/movie_detail_screen.dart
  lib/features/movies/viewmodel/movie_detail_viewmodel.dart
  lib/features/movies/widgets/movie_detail_header.dart
  lib/features/movies/widgets/synopsis_text.dart
  pubspec.lock
  pubspec.yaml
Labels: ui, refactor, fix

#77 [Refactor/ORDER-001] 주문 내역 & 주문 상세 내역 & 리뷰 쓰기 & 배송 조회
  lib/core/model/pagination.dart
  lib/features/mypage/detail/my_page_detail_screen.dart
  lib/features/mypage/detail/widget/create_review_widget.dart
  lib/features/mypage/detail/widget/order_detail_widget.dart
  lib/features/mypage/detail/widget/order_history_widget.dart
  lib/features/mypage/detail/widget/order_tracking_widget.dart
  lib/features/mypage/model/order/order.dart
  lib/features/mypage/model/order/order_item.dart
  lib/features/mypage/model/order/order_review.dart
  lib/features/mypage/model/order/order_review_image.dart
  lib/features/mypage/model/orderdetail/order_detail.dart
  lib/features/mypage/model/orderdetail/order_detail_item.dart
  lib/features/mypage/model/orderdetail/order_detail_review.dart
  lib/features/mypage/model/review_request.dart
  lib/features/mypage/repository/order_detail_repository.dart
  lib/features/mypage/repository/order_repository.dart
  lib/features/mypage/repository/order_status_repository.dart
  lib/features/mypage/repository/review_repository.dart
  lib/features/mypage/screen/my_page_screen.dart
  lib/features/mypage/service/order_service.dart
  lib/features/mypage/service/order_status_service.dart
  lib/features/mypage/service/review_service.dart
  lib/features/mypage/viewmodel/order_detail_viewmodel.dart
  lib/features/mypage/viewmodel/order_status_viewmodel.dart
  lib/features/mypage/viewmodel/order_viewmodel.dart
  lib/features/mypage/viewmodel/review_viewmodel.dart
  pubspec.yaml
Labels: feature, ui, refactor

#78 [refactor/REVIEW-002] review 없을 시 기본 이미지 적용하도록 변경 및 리뷰 사진 적용 정상적으로 작동
  lib/widgets/review_item.dart
Labels: refactor

#79 [refactor/REVIEW-004] 리뷰 수정 시 이미지 제한 처리
  lib/features/mypage/detail/widget/fix_review_widget.dart
Labels: refactor

#81 [Feat/fav-003&004] 영화 찜 추가/삭제 기능 및 찜 목록 조회 기능 구현
  lib/features/favorite/repository/favorite_repository.dart
  lib/features/favorite/screen/favorite_screen.dart
  lib/features/favorite/service/favorite_service.dart
  lib/features/favorite/viewmodel/favorite_viewmodel.dart
  lib/features/home/widgets/best_movie_widget.dart
  lib/features/movies/screen/movie_detail_screen.dart
  lib/features/movies/service/movies_service.dart
  lib/main.dart
  lib/widgets/common_gridview.dart
  lib/widgets/goods_item.dart
  lib/widgets/movie_item.dart
  pubspec.lock
Labels: feature

#84 [fix/movieName-in-goods-item] goods_item.dart에 movieTitle 출력
  lib/features/favorite/screen/favorite_screen.dart
  lib/features/goods/repository/goods_repository.dart
  lib/features/goods/services/goods_service.dart
  lib/features/goods/viewmodel/goods_all_viewmodel.dart
  lib/features/goods/widget/recommend_goods_widget.dart
  lib/features/home/widgets/best_goods_widget.dart
  lib/features/home/widgets/build_best_goods_grid.dart
  lib/widgets/common_gridview.dart
  lib/widgets/goods_item.dart
Labels: fix

#88 [fix/goods-soldout] 재고 없는 경우 예외처리
  lib/features/goods/widget/recommend_goods_widget.dart
  lib/features/home/widgets/best_goods_widget.dart
  lib/features/home/widgets/build_best_goods_grid.dart
  lib/widgets/common_gridview.dart
  lib/widgets/goods_item.dart
Labels: fix

#89 [fix/g02-goodsName-and-price] 굿즈명 길이, 줄 제한 & 가격, 평점의 위치 변경
  lib/features/goods/widget/header_goods_detail.dart
Labels: fix

#90 [fix/g02-detail] 상세설명의 길이 검증 로직 추가 및 상세설명이 없는 경우 기본값 추가
  lib/features/goods/widget/tabs_detail.dart
  lib/widgets/expandable_text.dart
Labels: fix

#91 [fix/g02-delivery-inquiry] 배송&환불, 문의 탭에 기본값 추가
  lib/features/goods/widget/tabs_delivery_refund.dart
  lib/features/goods/widget/tabs_inquiry.dart
Labels: fix

#80 [Fix/purchase 001]
  lib/core/storage/token_storage.dart
  lib/features/auth/viewmodel/my_page_viewmodel.dart
  lib/features/cart/screen/cart_screen.dart
  lib/features/cart/service/cart_service.dart
  lib/features/cart/viewmodel/cart_viewmodel.dart
  lib/features/cart/widgets/cart_bottom_bar_widgets.dart
  lib/features/cart/widgets/cart_item_tile.dart
  lib/features/cart/widgets/cart_item_widgets.dart
  lib/features/goods/screen/goods_detail_screen.dart
  lib/features/goods/widget/bottom_buttons_widget.dart
  lib/features/login/screen/login_screen.dart
  lib/features/mypage/screen/my_page_screen.dart
  lib/features/purchase/screen/purchase_screen.dart
  lib/features/purchase/service/purchase_service.dart
  lib/features/purchase/viewmodel/purchase_viewmodel.dart
  lib/features/purchase/widgets/delivery_info_cart.dart
  lib/features/purchase/widgets/goods_summary_card.dart
  lib/features/search/screen/search_screen.dart
  lib/features/search/viewmodel/search_view_model.dart
  lib/main.dart
  lib/widgets/main_app_bar.dart
Labels: feature, ui, refactor, fix

#93 [fix/f01-f02-merge-fix] 잘못된 merge 수정
  lib/features/favorite/screen/favorite_screen.dart
Labels: fix

#94 [fix/MV-02] 출연진 네트워크 실패 시 기본 이미지 처리
  lib/features/movies/widgets/cast_item.dart
  pubspec.lock
Labels: ui, refactor, fix

#99 [fix/MOVIE-002] 굿즈 상세 페이지 추천 굿즈 오류 수정
  lib/features/goods/repository/goods_recommended_repository.dart
  lib/features/goods/viewmodel/goods_recommended_viewmodel.dart
  lib/features/goods/widget/recommend_goods_widget.dart
Labels: fix

#103 [fix/REVIEW-004] 리뷰 이미지 통신 연동
  lib/features/goods/screen/goods_review_screen.dart
  lib/features/goods/viewmodel/goods_review_viewmodel.dart
  lib/features/goods/widget/tabs_review.dart
Labels: fix

#105 [fix/FAV-004-mv02] 영화 상세화면에서 찜 추가 시 에러 토스트 출력 (굿즈가 존재하지 않는 영화)
  lib/features/goods/widget/primary_image_widget.dart
  lib/features/movies/screen/movie_detail_screen.dart
  lib/widgets/goods_item.dart
  lib/widgets/movie_item.dart
  pubspec.lock
Labels: refactor, fix

#112 [Feat/password-change] 비밀번호 변경 UI, API 구현
  lib/features/auth/repository/auth_repository.dart
  lib/features/auth/service/auth_service.dart
  lib/features/auth/viewmodel/my_page_viewmodel.dart
  lib/features/auth/viewmodel/sign_up_viewmodel.dart
  lib/features/login/screen/login_screen.dart
  lib/features/mypage/detail/my_page_detail_screen.dart
  lib/features/mypage/detail/widget/edit_password_widget.dart
  lib/features/mypage/detail/widget/edit_profile_widget.dart
  lib/features/mypage/screen/my_page_screen.dart
  lib/features/signup/screen/sign_up_screen.dart
Labels: feature, ui

#106 [fix/boxoffice] boxoffice 크기 조절 및 애니메이션 처리
  lib/features/home/widgets/box_office_ranking_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: refactor, fix

#111 [fix/REVIEW-004-effect] 굿즈 리뷰 목록 화면에서 좋아요/싫어요 이벤트 처리 강화
  lib/features/goods/screen/goods_review_screen.dart
  lib/widgets/review_item.dart
Labels: fix

#114 [fix/outofstock] 품절 임박 텍스트 처리
  lib/widgets/goods_item.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, refactor

#117 [Fix/error handling] 모든 부분의 에러 처리..
  lib/features/cart/screen/cart_screen.dart
  lib/features/cart/widgets/cart_empty_view_widgets.dart
  lib/features/cart/widgets/cart_item_tile.dart
  lib/features/goods/screen/goods_all_screen.dart
  lib/features/goods/screen/goods_review_screen.dart
  lib/features/goods/widget/common_tabs_content.dart
  lib/features/goods/widget/recommend_goods_widget.dart
  lib/features/home/model/best_goods.dart
  lib/features/movies/screen/movies_screen.dart
  lib/features/movies/service/movies_service.dart
  lib/features/movies/widgets/build_best_goods_grid.dart
  lib/features/movies/widgets/movie_detail_header.dart
  lib/features/mypage/detail/widget/my_review_widget.dart
  lib/features/mypage/detail/widget/order_detail_widget.dart
  lib/features/mypage/detail/widget/order_history_widget.dart
  lib/features/mypage/detail/widget/order_tracking_widget.dart
  lib/widgets/common_gridview.dart
  lib/widgets/common_tab_view.dart
  lib/widgets/goods_item.dart
  lib/widgets/loading_view.dart
  lib/widgets/retry_view.dart
  pubspec.lock
Labels: refactor, fix

#120 [fix/g02-tirm-delivery-refund] 배송&환불로 공백 제거
  lib/features/goods/screen/goods_detail_screen.dart
  pubspec.lock
Labels: fix

#121 [fix/logger-image-err] Logger를 통한 이미지 로그 출력 코드 삭제
  lib/features/goods/screen/goods_review_screen.dart
  lib/features/goods/viewmodel/goods_review_viewmodel.dart
Labels: fix

#122 [Fix/search final] 검색 진짜 최종본
  lib/features/search/screen/search_screen.dart
  lib/features/search/widgets/search_common_gridView.dart
Labels: fix

#123 [fix/order_detail] 주문 상세 버튼 -> 비활성화로 변경
  lib/features/mypage/detail/widget/order_detail_widget.dart
Labels: feature, refactor

#126 [fix/fav-toast-movie-empty-screen] 찜 토글 시의 토스트 텍스트 수정 및 영화 찜이 없는 경우 대체 화면 출력
  lib/features/favorite/screen/favorite_screen.dart
  lib/features/favorite/viewmodel/favorite_viewmodel.dart
  lib/widgets/goods_item.dart
  lib/widgets/movie_item.dart
Labels: fix

#130 [fix/mypage_screen_email] 이메일 픽셀 짤림
  lib/features/mypage/screen/my_page_screen.dart
Labels: fix

#132 [Fix/cartfinal] 장바구니 삭제/ 구매 완료시 화면 이동 진짜 최종본...
  lib/features/cart/screen/cart_screen.dart
  lib/features/purchase/screen/purchase_screen.dart
Labels: fix

#135 [fix/r03-like-dislike] 리뷰의 좋아요 / 싫어요 출력 수정
  lib/features/goods/screen/goods_review_screen.dart
  lib/widgets/review_item.dart
Labels: fix

#139 [fix/refreshToken] refreshToken 처리
  lib/core/network/api_client.dart
Labels: fix
